

option("libdir")
    add_deps("outputdir")
    set_showmenu(false)
    on_check(function (option)
        option:set_value(path.translate(vformat("$(outputdir)/lib", xmake)))
    end)
option_end()

option("bindir")
    add_deps("outputdir")
    set_showmenu(false)
    on_check(function (option)
        option:set_value(path.translate(vformat("$(outputdir)/bin", xmake)))
    end)
option_end()

option("testdir")
    add_deps("outputdir")
    set_showmenu(false)
    on_check(function (option)
        option:set_value(path.translate(vformat("$(outputdir)/test", xmake)))
    end)
option_end()

option("pdbdir")
    add_deps("outputdir")
    set_showmenu(false)
    on_check(function (option)
        option:set_value(path.translate(vformat("$(outputdir)/pdb", xmake)))
    end)
option_end()

option("plugindir")
    add_deps("outputdir")
    set_showmenu(false)
    on_check(function (option)
        option:set_value(path.translate(vformat("$(outputdir)/plugin", xmake)))
    end)
option_end()